## Importing `Numpy`

In [21]:
import numpy as np

That's all, folks!

## Creating arrays

In [22]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

### Functions
Arrays can be created with `arange`, `linspace`, `ones`, `zeros`, `eye` and `diag`.

In [23]:
b = np.ones(4)
b

array([ 1.,  1.,  1.,  1.])

In [24]:
j = np.arange(5)
j

array([0, 1, 2, 3, 4])

In [25]:
c = np.ones((3, 3))
c

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### 2D arrays

In [26]:
h = np.array([[1, 1, 2], [3, 5, 8]])
h

array([[1, 1, 2],
       [3, 5, 8]])

### Empty arrays

In [27]:
o = np.empty(3)
o

array([  4.94065646e-324,   9.88131292e-324,   1.48219694e-323])

In [28]:
e = np.empty([5, 2])
e

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

## Basic functions

* `ndim`: number of dimensions,
* `shape`: sizes of dimensions,
* `len()`: size of first dimension

In [29]:
len(h)

2

In [30]:
h.shape

(2, 3)

In [31]:
h.ndim

2

## Comparing arrays

In [71]:
a = np.arange(0, 4) + 1 # a = [1, 2, 3, 4]
b = np.array([4, 2, 2, 4])

In [33]:
a > b

array([False, False,  True, False], dtype=bool)

In [34]:
a == b

array([False,  True, False,  True], dtype=bool)

### Array-wise comparisons

In [35]:
np.array_equal(a, b)

False

In [72]:
np.array_equal(a, [1, 2, 3, 4])

True

### Logical operations

In [74]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

Since we've defined `dtype`, `a` is an array of `bool`s (as well as `b`, actually):

In [75]:
a

array([ True,  True, False, False], dtype=bool)

In [38]:
np.logical_or(a, b)

array([ True,  True,  True, False], dtype=bool)

In [39]:
np.logical_and(a, b)

array([ True, False, False, False], dtype=bool)

## Statistical Analysis

### Random
Create a `[2 x 3]` matrix filled with random floats in range `[0, 1]`:

In [165]:
data_set = np.random.random((2, 3))
data_set

array([[ 0.32203612,  0.26970611,  0.31325521],
       [ 0.6681475 ,  0.69187175,  0.44113703]])

### Max & min

We can get max and min values with `np.max()` and `np.min()` functions.
Second argument, `axis`, can take an integer indexing to an axis (`0` - first dimensions, counts max/min of columns).

In [166]:
np.max(data_set)

0.69187174577662058

In [167]:
# Get max for each of the columns
np.max(data_set, axis = 0)

array([ 0.6681475 ,  0.69187175,  0.44113703])

In [168]:
# Get max for rows now
np.max(data_set, axis = 1)

array([ 0.32203612,  0.69187175])

### Some other functions

`np.mean()`, `np.median()`, `np.std()`, `np.sum()` work the same way

In [ ]:
print(np.mean(data_set))

print(np.median(data_set))

print(np.std(data_set))

print(np.sum(data_set))

## Reshaping 

When reshaping with function `reshape()`:

- first arg: data set (`np.array`)
- second arg: new shape _(rows * columns)_ or _(len of 1D array)_

In [56]:
np.reshape(data_set, (3, 2))

array([[ 0.97976311,  0.1050908 ],
       [ 0.40782487,  0.62501515],
       [ 0.85184276,  0.38211203]])

In [57]:
np.reshape(data_set, (6, 1))

array([[ 0.97976311],
       [ 0.1050908 ],
       [ 0.40782487],
       [ 0.62501515],
       [ 0.85184276],
       [ 0.38211203]])

In [58]:
np.reshape(data_set, 6)

array([ 0.97976311,  0.1050908 ,  0.40782487,  0.62501515,  0.85184276,
        0.38211203])

Function `ravel` returns a contiguous flattened array.

In [59]:
np.ravel(data_set)

array([ 0.97976311,  0.1050908 ,  0.40782487,  0.62501515,  0.85184276,
        0.38211203])

## Indexing & slicing

In [112]:
# Create a (5 rows * 6 columns) 2D array.
data_set = np.random.randint(0, 100, (5, 6))
data_set

array([[57, 48, 75, 89, 45, 88],
       [92, 60, 60,  2, 53, 56],
       [85, 16, 42, 26, 24,  7],
       [40,  3, 70,  2, 70, 40],
       [11,  7, 52, 26, 71,  2]])

### Indexing

Takes second (`index = 1`) row:

In [113]:
data_set[1]

array([92, 60, 60,  2, 53, 56])

Takes 1st (index 0) element of the 2nd (index 1) row:

In [114]:
data_set[1][0]

92

In [115]:
data_set[1, 0]

92

### Slicing a range

In [116]:
data_set[2:4] # rows 3-4

array([[85, 16, 42, 26, 24,  7],
       [40,  3, 70,  2, 70, 40]])

In [117]:
data_set[2:4, 0] # rows 3-4, first column only 

array([85, 40])

In [118]:
data_set[2:4, 0:2] # takes rows number 3 to 4 and selects first 2 columns from them

array([[85, 16],
       [40,  3]])

### Slicing with steps

In [119]:
data_set[2:4:1] # rows 3-4 and every 1st column

array([[85, 16, 42, 26, 24,  7],
       [40,  3, 70,  2, 70, 40]])

In [120]:
data_set[::] # everything

array([[57, 48, 75, 89, 45, 88],
       [92, 60, 60,  2, 53, 56],
       [85, 16, 42, 26, 24,  7],
       [40,  3, 70,  2, 70, 40],
       [11,  7, 52, 26, 71,  2]])

In [124]:
data_set[::-1] # everything reverse

array([[11,  7, 52, 26, 71,  2],
       [40,  3, 70,  2, 70, 40],
       [85, 16, 42, 26, 24,  7],
       [92, 60, 60,  2, 53, 56],
       [57, 48, 75, 89, 45, 88]])

In [122]:
data_set[2:4, ::2] # rows 3-4 and every 2nd column (columns 1, 3, 5, 7, 9)

array([[85, 42, 24],
       [40, 70, 70]])

### Fancy indexing

Fancy indexing allows to use masks (arrays of boolean or integer values).

In [144]:
# Create a 1d array
np.random.seed(140)
a = np.random.randint(0, 100, 10)
print(a)
print(a.mean())
print(a >= a.mean())

[38 23 22 77 80 32 59 57 35 21]
44.4
[False False False  True  True False  True  True False False]


In [141]:
# Create a mask
mask = (a >= a.mean())

# Apply it
print(a[mask])
a[mask] = 900
print(a)

[53 87 72 67 49]
[900  17 900   9 900 900  34  10   5 900]


### Indexing with a list

In [147]:
# Create a 1d array
np.random.seed(142)
a = np.random.randint(0, 100, 10)
print(a)

[21 69 27 12 26 45 80 49 13 34]


In [148]:
# Create indexes - a list of integers
indexes = [0, 2, 7, 9, 2, 4]

In [149]:
a[indexes]

array([21, 27, 49, 34, 27, 26])

In [150]:
a[[1, 1, 1]]

array([69, 69, 69])

## Elementwise operations

In [154]:
a = np.arange(4)

print(a)
print(a + 1)
print(a * 2.5)
print(a / 10)

[0 1 2 3]
[1 2 3 4]
[ 0.   2.5  5.   7.5]
[ 0.   0.1  0.2  0.3]


Two vectors:

In [159]:
b = np.arange(8,12)

print(b)
print(a + b)
print(a * b)
print(a / b)

[ 8  9 10 11]
[ 8 10 12 14]
[ 0  9 20 33]
[ 0.          0.11111111  0.2         0.27272727]


### Transcendential functions

In [160]:
a = np.arange(1, 5)

In [161]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [162]:
np.log(a)

array([ 0.        ,  0.69314718,  1.09861229,  1.38629436])

In [163]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

### Shape mismatches

In [ ]:
try:
    a + np.array([1, 2])
except ValueError:
    print("ValueError: operands could not be broadcast together with shapes (4,) (2,)")

### Transposition

In [ ]:
a = np.triu(np.ones((3, 3)), 1) 
help(np.triu)

In [ ]:
print(a)

In [96]:
print(a.T)