# 100 Julia exercises

Source: https://github.com/chezou/julia-100-exercises

> This is Julia version of [100 numpy exercises](http://www.loria.fr/~rougier/teaching/numpy.100/)

> Latest version of 100 numpy excercises are available at [this repository](https://github.com/rougier/numpy-100).

> You can see executed results [here](http://nbviewer.ipython.org/github/chezou/julia-100-exercises/blob/master/julia-100-exercises.ipynb)

-----------------

## Neophyte

### 2. Print the Julia version

In [3]:
VERSION

v"0.4.3"

### 3. Create a null vector of size 10

In [4]:
z = zeros(10)

10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

### 4. Create a null vector of size 10 and set the fifth value to 1

In [7]:
z = zeros(10)
z[5] = 1

z

10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0

### 5. Create a vector with values ranging from 10 to 99

In [1]:
v = [10:99]

90-element Array{Int64,1}:
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21
 22
  ⋮
 88
 89
 90
 91
 92
 93
 94
 95
 96
 97
 98
 99

 in depwarn at deprecated.jl:73
 in oldstyle_vcat_warning at /usr/local/Cellar/julia/0.4.3/lib/julia/sys.dylib
 in vect at abstractarray.jl:32
 in include_string at loading.jl:266
 in execute_request_0x535c5df2 at /Users/mac/.julia/v0.4/IJulia/src/execute_request.jl:177
 in eventloop at /Users/mac/.julia/v0.4/IJulia/src/IJulia.jl:141
 in anonymous at task.jl:447
while loading In[1], in expression starting on line 1


### 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
m = reshape(0:8, 3, 3)

3x3 Array{Int64,2}:
 0  3  6
 1  4  7
 2  5  8

### 7. Find indices of non-zero elements from [1,2,0,0,4,0]

In [12]:
nz = find([1, 2, 0, 0, 4, 0])

3-element Array{Int64,1}:
 1
 2
 5

### 8. Create a 3x3 identity matrix

In [13]:
e = eye(3)

3x3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

### 9. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [14]:
m = diagm(1:4, -1)

5x5 Array{Int64,2}:
 0  0  0  0  0
 1  0  0  0  0
 0  2  0  0  0
 0  0  3  0  0
 0  0  0  4  0

### 10. Create a 10x10x10 array with random values

In [15]:
rand(10, 10, 10)

10x10x10 Array{Float64,3}:
[:, :, 1] =
 0.459613   0.533373  0.148516   0.663429   …  0.156148  0.859446  0.0886111
 0.502602   0.237709  0.0385582  0.841692      0.519103  0.415616  0.236542 
 0.196077   0.573261  0.925178   0.350489      0.326767  0.165404  0.69827  
 0.0795486  0.19438   0.478645   0.288867      0.473446  0.518264  0.616707 
 0.761796   0.756389  0.168613   0.391024      0.181694  0.535621  0.631807 
 0.501686   0.535566  0.0921788  0.696437   …  0.334407  0.915345  0.598979 
 0.882091   0.463479  0.818101   0.368462      0.873294  0.265484  0.495247 
 0.383507   0.715665  0.437152   0.875677      0.662119  0.703248  0.409473 
 0.975296   0.60797   0.971256   0.0322134     0.907483  0.569797  0.505201 
 0.124441   0.320871  0.498543   0.570147      0.28563   0.559385  0.473202 

[:, :, 2] =
 0.651319  0.611508   0.408661   0.0521751  …  0.452725  0.756983   0.9223   
 0.124851  0.690753   0.0387292  0.239478      0.52297   0.829906   0.523899 
 0.365384  0.489322   

## Novice

### 1. Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
Z = zeros(8, 8)
Z[1:2:end, 2:2:end] = 1
Z[2:2:end, 1:2:end] = 1
Z

8x8 Array{Float64,2}:
 0.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0
 1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0
 0.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0
 1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0
 0.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0
 1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0
 0.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0
 1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0

### 2. Create a 10x10 array with random values and find the minimum and maximum values

In [2]:
Z = rand(10, 10)

print(minimum(Z), maximum(Z))
print("\n----\n")
print("\n----\n")
print(extrema(Z))
print("\n----\n")
Zmin, Zmax = extrema(Z)

0.0

(0.00297307599754415,0.9931576949204739)

02973075997544150.9931576949204739
----

----
(0.00297307599754415,0.9931576949204739)
----


### 3. Create a checkerboard 8x8 matrix using the tile function

In [4]:
Z = repmat([0 1;1 0], 4, 4)

8x8 Array{Int64,2}:
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0

### 4. Normalize a 5x5 random matrix (between 0 and 1)

In [5]:
Z = rand(5, 5)
Zmin, Zmax = extrema(Z)
Z = (Z .- Zmin)./(Zmax - Zmin)

5x5 Array{Float64,2}:
 0.852398  0.0       0.890332  0.987397  0.976735 
 0.433485  0.321928  0.770248  0.877759  0.787189 
 0.775723  0.556742  0.148721  0.895274  0.863211 
 0.465847  0.86465   0.828993  0.68005   0.0817061
 0.209168  0.405381  0.491926  0.629073  1.0      

### 5. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [6]:
Z = ones(5, 3) * ones(3, 2)

5x2 Array{Float64,2}:
 3.0  3.0
 3.0  3.0
 3.0  3.0
 3.0  3.0
 3.0  3.0

### 6. Create a 10x10 matrix with row values ranging from 0 to 9

In [9]:
Z = [y for x in 1:10, y in 0:9]

10x10 Array{Int64,2}:
 0  1  2  3  4  5  6  7  8  9
 0  1  2  3  4  5  6  7  8  9
 0  1  2  3  4  5  6  7  8  9
 0  1  2  3  4  5  6  7  8  9
 0  1  2  3  4  5  6  7  8  9
 0  1  2  3  4  5  6  7  8  9
 0  1  2  3  4  5  6  7  8  9
 0  1  2  3  4  5  6  7  8  9
 0  1  2  3  4  5  6  7  8  9
 0  1  2  3  4  5  6  7  8  9

### 7. Create a vector of size 1000 with values ranging from 0 to 1, both excluded

In [10]:
linspace(0, 1, 1002)[2:end - 1]

linspace(0.000999000999000999,0.999000999000999,1000)

### 8. Create a random vector of size 100 and sort it

In [12]:
v = rand(100)
# sort(v)
sort!(v) # sort v and save the result to v

100-element Array{Float64,1}:
 0.00724294
 0.0145325 
 0.0148629 
 0.0579311 
 0.0806452 
 0.0907783 
 0.0946269 
 0.102515  
 0.140644  
 0.143046  
 0.15323   
 0.156139  
 0.158173  
 ⋮         
 0.922119  
 0.926881  
 0.928186  
 0.930573  
 0.940174  
 0.942797  
 0.950314  
 0.971311  
 0.972312  
 0.97234   
 0.973647  
 0.981324  

### 9. Consider two random matrices A anb B, check if they are equal.

In [24]:
A = rand(0:2, 2, 2)
B = rand(0:2, 2, 2)

A == B

false

### 10. Create a random vector of size 1000 and find the mean value

In [15]:
v = rand(1000)
mean(v)

0.5006005459056813

## Apprentice

### 1. Make an array immutable (read-only)

### 2. Consider a random 10x2 matrix representing Cartesian coordinates, convert them to polar coordinates

In [ ]:
Z = rand(10, 2)

### 3. Create random vector of size 100 and replace the maximum value by 0

In [25]:
v = rand(100)
v[indmax(v)] = 0

0

### 4. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area.

In [26]:
[(x, y) for x in linspace(0,1,10), y in linspace(0,1,10)]

10x10 Array{Tuple{Float64,Float64},2}:
 (0.0,0.0)                 …  (0.0,1.0)               
 (0.1111111111111111,0.0)     (0.1111111111111111,1.0)
 (0.2222222222222222,0.0)     (0.2222222222222222,1.0)
 (0.3333333333333333,0.0)     (0.3333333333333333,1.0)
 (0.4444444444444444,0.0)     (0.4444444444444444,1.0)
 (0.5555555555555556,0.0)  …  (0.5555555555555556,1.0)
 (0.6666666666666666,0.0)     (0.6666666666666666,1.0)
 (0.7777777777777778,0.0)     (0.7777777777777778,1.0)
 (0.8888888888888888,0.0)     (0.8888888888888888,1.0)
 (1.0,0.0)                    (1.0,1.0)               

### 5. Print the minimum and maximum representable value for each Julia scalar type

### 6. Create a structured array representing a position (x,y) and a color (r,g,b)

### 7. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

### 8. Generate a generic 2D Gaussian-like array

### 9. Consider the vector [1, 2, 3, 4, 5]. How to build a new vector with 3 consecutive zeros interleaved between each value?

### 10. Find the nearest value from a given value in an array

## Journeyman

### 1. Consider the following file:

```
1,2,3,4,5
6,,,7,8
,,9,10,11
```

### How to read it?

### 2. Consider a generator function that generates 10 integers and use it to build an array

### 3. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

### 4. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

### 5. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

### 6. Considering a four dimensional array, how to get sum over the last two axis at once?

### 7. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?

## Craftsman
### 1. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

### 2. Consider a set of 100 triplets describing 100 triangles (with shared vertices), find the set of unique line segments composing all the triangles.

### 3. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C?

### 4. How to compute averages using a sliding window over an array?

## Artisan
### 1. Considering a 100x3 matrix, extract rows with unequal values (e.g. [2,2,3])

### 2. Convert a vector of ints into a matrix binary representation.

## Adept
### 1. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

## Expert
### 1. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

### 2. Extract all the contiguous 3x3 blocks from a random 10x10 matrix.

### 3. Create a 2D array subclass such that `Z[i,j] == Z[j,i]`

### 4. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of the p matrix products at once? (result has shape (n,1))

## Master
### 1. Given a two dimensional array, how to extract unique rows?

## Archmaster